In [1]:
import os
import sys
sys.path.append(os.path.join(os.getcwd(),"apperception"))

### IMPORTS
import cv2

from world import *
from world_executor import *
from video_util import *
from metadata_util import *
import lens

import psycopg2


In /home/yongming/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/yongming/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/yongming/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /home/yongming/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/yongming/.local/lib/python3.6/site-packages/matplotlib/

-> Loading model from  models/mono+stereo_640x192
   Loading pretrained encoder
   Loading pretrained decoder


In [2]:
### Let's define some attribute for constructing the world first
name = 'traffic_scene' # world name
units = 'metrics'      # world units
cam1_id = 'cam1'
cam1_video_file = "../visual_road_video_cut/traffic-001_clip_clip.mp4" #cam1 view
cam2_id = 'cam2'
cam2_video_file = "../visual_road_video_cut/traffic-002_clip_clip.mp4" #cam2 view

In [3]:
### First we define a world
traffic_world = World(name=name, units=units)

### Use TASM if it's available on the machine
# traffic_world = World(name=name, units=units, enable_tasm=True)

In [4]:
### Secondly we construct the camera
cam1_len = lens.VRLens(resolution=[3840, 2160], cam_origin=(199, -239, 5.2), yaw=-52, roll=0, pitch=0, field_of_view=90)
cam2_len = lens.VRLens(resolution=[3840, 2160], cam_origin=(210, -270, 9), yaw=128, roll=0, pitch=-30, field_of_view=90)
fps = 30

focal_width 1919.9999999999998
focal_height 1079.9999999999998
scaling matrix is [[ 5.20833333e-04  0.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  9.25925926e-04 -1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
focal_width 1919.9999999999998
focal_height 1079.9999999999998
scaling matrix is [[ 5.20833333e-04  0.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  9.25925926e-04 -1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [5]:
### Ingest the camera to the world
traffic_world = traffic_world.camera(cam_id=cam1_id, 
                               video_file=cam1_video_file, 
                               metadata_identifier=name+"_"+cam1_id, 
                               lens=cam1_len)

In [6]:
### Call execute on the world to run the detection algorithm and save the real data to the database
recognized_world = traffic_world.recognize(cam1_id)
recognized_world.execute()

Worlds Table created successfully........
New world inserted successfully........
Camera Table created successfully........
New camera inserted successfully.........
# of tracked items: 15
car-1 saved successfully
car-2 saved successfully
person-3 saved successfully
traffic light-4 saved successfully
traffic light-5 saved successfully
person-6 saved successfully
person-7 saved successfully
person-8 saved successfully
person-10 saved successfully
car-14 saved successfully
person-18 saved successfully
car-19 saved successfully
person-28 saved successfully
car-29 saved successfully
person-31 saved successfully


In [7]:
print(np.load("./left_top_1.npy"))
np.load("./left_top_2.npy")

[[ 198.22919408  198.23179199  198.23252163  198.23689946  198.23730845
   198.23949736  198.24031533  198.24104497  198.24063599  198.24063599
   198.23990635  198.23698779  198.23625815  198.23625815  198.23739677
   198.2374851   198.23789408  198.23342792  198.23164798]
 [-239.62714181 -239.62983246 -239.63040252 -239.63382286 -239.63480334
  -239.63651351 -239.63847447 -239.63904453 -239.63806405 -239.63806405
  -239.63749399 -239.63521376 -239.63464371 -239.63464371 -239.63619424
  -239.63758514 -239.63856562 -239.63375438 -239.63302469]
 [   6.2           6.2           6.2           6.2           6.2
     6.2           6.2           6.2           6.2           6.2
     6.2           6.2           6.2           6.2           6.2
     6.2           6.2           6.2           6.2       ]
 [   1.            1.            1.            1.            1.
     1.            1.            1.            1.            1.
     1.            1.            1.            1.            1.
    

array([[ 209.49711409,  209.49711409],
       [-269.55931449, -269.55931449],
       [  10.17644207,   10.17644207],
       [   1.        ,    1.        ]])

In [8]:
traffic_world = traffic_world.camera(cam_id=cam2_id, 
                               video_file=cam2_video_file, 
                               metadata_identifier=name+"_"+cam2_id, 
                               lens=cam2_len)
tracking_results = recognize(cam2_video_file)
conn = psycopg2.connect(database="mobilitydb", user="docker", password="docker", host="localhost", port=25432)


/home/yongming/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py:1751: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


# of tracked items: 9


In [9]:
add_recognized_objs(conn, cam2_len, tracking_results, traffic_world.VideoContext.start_time, temp=True)

car-1 saved successfully
car-2 saved successfully
person-3 saved successfully
traffic light-4 saved successfully
car-5 saved successfully
car-6 saved successfully
person-8 saved successfully
car-10 saved successfully
person-11 saved successfully


In [11]:
volume = traffic_world.select_intersection_of_interest_or_use_default(cam_id=cam1_id)
filtered_world = traffic_world.predicate(lambda obj:obj.object_type == "car")
# filtered_world = traffic_world.predicate(lambda obj:obj.object_type == "car").predicate(lambda obj:obj.location in volume, {"volume":volume})
# filtered_world = filtered_world.interval([0,fps*4])
 
### to get the trajectory and the video over the entire trajectory(amber case)
filtered_ids = filtered_world.selectkey(distinct = True).execute()
print("filtered_ids are", filtered_ids)
print(len(filtered_ids))
if len(filtered_ids)>0:
    id_array = [e[0] for e in filtered_ids]
    ### Fetch the trajectory of these items
    trajectory = traffic_world.predicate(lambda obj: obj.object_id in id_array, {"id_array":id_array}).get_trajectory(distinct=True).execute()
    traffic_world.overlay_trajectory(cam1_id, trajectory)
    ### Get the videos of these items
    entire_video = traffic_world.predicate(lambda obj: obj.object_id in id_array, {"id_array":id_array}).get_video()
    entire_video.execute()

{'cam1': <video_context.Camera object at 0x7f84024c3c50>, 'cam2': <video_context.Camera object at 0x7f84024c3eb8>}
Module(body=[Return(value=Compare(left=Attribute(value=Name(id='obj', ctx=Load()), attr='object_type', ctx=Load()), ops=[Eq()], comparators=[Str(s='car')]))])
Worlds Table created successfully........
New world inserted successfully........
Camera Table created successfully........
New camera inserted successfully.........
Camera Table created successfully........
New camera inserted successfully.........
SELECT distinct on(itemId) Item_General_Trajectory.itemId From Item_General_Trajectory  Where Item_General_Trajectory.objectType='car';

filtered_ids are [['car-1']
 ['car-14']
 ['car-19']
 ['car-2']
 ['car-29']]
5
Module(body=[Return(value=Compare(left=Attribute(value=Name(id='obj', ctx=Load()), attr='object_id', ctx=Load()), ops=[In()], comparators=[Name(id='id_array', ctx=Load())]))])
Worlds Table created successfully........
New world inserted successfully........
Cam

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)