In [34]:
import numpy as np
import torch

from postgis import MultiPoint
from bitarray import bitarray

In [2]:
np.array(['a', 'b', 'c'])

array(['a', 'b', 'c'], dtype='<U1')

In [3]:
np.array(['a', 'b', 'c'])[[0, 2]]

array(['a', 'c'], dtype='<U1')

In [4]:
np.array(['a', 'b', 'c'])[[0, 2]].tolist()

['a', 'c']

In [7]:
a = torch.Tensor([1,2,3,4])

In [8]:
a[0]

tensor(1.)

In [9]:
int(a[0])

1

In [10]:
na = np.array

In [12]:
a = na([[1, 0], [0, 1]])
a

array([[1, 0],
       [0, 1]])

In [13]:
b = na([[2, 0], [0, 1]])
b

array([[2, 0],
       [0, 1]])

In [14]:
c = na([[3, 0], [0, 1]])
c

array([[3, 0],
       [0, 1]])

In [15]:
np.concatenate([a, b, c])

array([[1, 0],
       [0, 1],
       [2, 0],
       [0, 1],
       [3, 0],
       [0, 1]])

In [17]:
m1 = np.stack([a, b, c])
m1

array([[[1, 0],
        [0, 1]],

       [[2, 0],
        [0, 1]],

       [[3, 0],
        [0, 1]]])

In [18]:
m1.shape

(3, 2, 2)

In [19]:
m1 @ m1

array([[[1, 0],
        [0, 1]],

       [[4, 0],
        [0, 1]],

       [[9, 0],
        [0, 1]]])

In [20]:
m1 @ a

array([[[1, 0],
        [0, 1]],

       [[2, 0],
        [0, 1]],

       [[3, 0],
        [0, 1]]])

In [22]:
m1 @ b

array([[[2, 0],
        [0, 1]],

       [[4, 0],
        [0, 1]],

       [[6, 0],
        [0, 1]]])

In [24]:
MultiPoint([[1,2], [3,4]])

<MultiPoint MULTIPOINT((1.0 2.0), (3.0 4.0))>

In [26]:
MultiPoint(m1 @ b)

TypeError: only size-1 arrays can be converted to Python scalars

In [31]:
MultiPoint((m1  @ b).tolist()[0])

<MultiPoint MULTIPOINT((2.0 0.0), (0.0 1.0))>

In [29]:
MultiPoint([[2, 0], [0, 1]])

<MultiPoint MULTIPOINT((2.0 0.0), (0.0 1.0))>

In [32]:
MultiPoint((m1  @ b)[0].tolist())

<MultiPoint MULTIPOINT((2.0 0.0), (0.0 1.0))>

In [35]:
a = bitarray(10)

In [36]:
a

bitarray('1111000011')

In [37]:
a.setall(0)

In [38]:
a

bitarray('0000000000')

In [39]:
a[[2,6,7]] = 1

TypeError: bitarray indices must be integers or slices, not list

In [40]:
np.hstack([na([[1,2],[3,4]]), na([9,10])[np.newaxis].T])

array([[ 1,  2,  9],
       [ 3,  4, 10]])

In [41]:
width, height = 1600, 900

In [42]:
Z = 10
point_2ds = Z * np.array([
    # 4 corners of the image frame
    (width, height, 1),
    (width, 0, 1),
    (0, height, 1),
    (0, 0, 1),
]).T

In [43]:
point_2ds

array([[16000, 16000,     0,     0],
       [ 9000,     0,  9000,     0],
       [   10,    10,    10,    10]])

In [52]:
np.concatenate((point_2ds, np.ones((1, point_2ds.shape[1]))))

array([[1.6e+04, 1.6e+04, 0.0e+00, 0.0e+00],
       [9.0e+03, 0.0e+00, 9.0e+03, 0.0e+00],
       [1.0e+01, 1.0e+01, 1.0e+01, 1.0e+01],
       [1.0e+00, 1.0e+00, 1.0e+00, 1.0e+00]])